# Develop the machine learning model to predict the patient is having diabets or not


In [ ]:
import pandas as pd
import numpy as np

In [3]:
a = pd.read_csv("Dataset-diabetes.csv")

In [4]:
a.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [8]:
a.head(7)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1

In [9]:
a

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [10]:
a.shape 

(768, 9)

In [11]:
a.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
#split the data into independent and dependent variable 
X=a.drop('Outcome',axis=1) #Dependent -> Input 
y=a['Outcome'] #independent -> Output 

In [23]:
#train tet split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=20)

In [24]:
#Selection and train our model  
from sklearn.tree import DecisionTreeClassifier 

In [25]:
mymodel = DecisionTreeClassifier()
mymodel

DecisionTreeClassifier()

In [26]:
#Train the model 
result=mymodel.fit(X_train,y_train)

In [27]:
pred=result.predict(X_test)
pred

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0])

In [28]:
import warnings
warnings.filterwarnings("ignore")

In [31]:
print('Validation accuracy score is',accuracy_score(y_test,pred))

Validation accuracy score is 0.6692913385826772


In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.77      0.73      0.75       171
           1       0.49      0.54      0.52        83

    accuracy                           0.67       254
   macro avg       0.63      0.64      0.63       254
weighted avg       0.68      0.67      0.67       254



In [36]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[125,  46],
       [ 38,  45]])

In [37]:
pred1=result.predict([[4,156,76,36,0,36,0.65,51]])
pred1

array([1])

In [39]:
#KNN Algorithm 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
#checking the validation score or test score 
print('Validation accuaracy score with KNN is',accuracy_score(y_test,pred))

Validation accuaracy score with KNN is 0.7440944881889764


In [40]:
#KNN Algorithm 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
#checking the validation score or test score 
print('Validation accuaracy score with KNN is',accuracy_score(y_test,pred))

Validation accuaracy score with KNN is 0.7086614173228346


In [44]:
#KNN Algorithm 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
#checking the validation score or test score 
print('Validation accuaracy score with KNN is',accuracy_score(y_test,pred))

Validation accuaracy score with KNN is 0.7440944881889764


In [45]:
#KNN Algorithm 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=11)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
#checking the validation score or test score 
print('Validation accuaracy score with KNN is',accuracy_score(y_test,pred))

Validation accuaracy score with KNN is 0.7559055118110236


In [46]:
#KNN Algorithm 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=12)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
#checking the validation score or test score 
print('Validation accuaracy score with KNN is',accuracy_score(y_test,pred))

Validation accuaracy score with KNN is 0.7440944881889764


In [47]:
#Random forest 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
#X_train=sc.fit_transform(X_train)
#X_test=sc.transform(X_test)

from sklearn.ensemble import RandomForestClassifier
mymodel2=RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=88)
result2=mymodel2.fit(X_train,y_train)
pred=result2.predict(X_test)
accuracy_score(pred,y_test)

0.7677165354330708